### PR TITLE
fix: extend origin check for vscode servers

### LINKED ISSUE #625: Websocket connection for preview on code-server
**Describe the bug**

When using the extension on code-server the preview tries to connect to localhost instead of the proxy url.

**Description**

It would be nice to set the websocket path for the lsp to connect to because automatically getting it seems complex or impossible becasue it is configurable in code-server.

**Examples/Questions**

- Becasue the proxy url can be configured to be a subpath or a subdomain it would be nice to change to either method with a switch (Radio button) and configure it
  1. Localhost
  2. Subdomain
  3. Subpath
- Raising questions to highlight the uncertain design for the *feature*.

**Package/Software version:**

code-server version(Help -> About):
docker image: codercom/code-server:4.93.1-ubuntu
```plain
code-server: v4.93.1
Code: 1.93.1
Commit: 3542bd157b0ccc8bf732acdb03d4d69d85f48ea9
Date: 2024-09-19T10:15:30.023Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
```

tinymist extension version: `v0.11.22`. Get it by `tinymist --version` in terminal.
as bundeled with the extension of this version
```plain
tinymist 
Build Timestamp:     2024-09-27T23:50:57.941849314Z
Build Git Describe:  v0.11.22
Commit SHA:          f3ccb4a18618fcf51d2ada8217629c58783e338c
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
Typst Version:       0.11.1
```

**Logs:**

tinymist server log(Output Panel -> tinymist):
```plain
[Trace - 9:20:36 AM] Sending request 'initialize - (0)'.
[2024-10-03T09:20:36Z INFO  tinymist] starting LSP server: LspArgs {
        mirror: MirrorArgs {
            mirror: "",
            replay: "",
        },
        font: CompileFontArgs {
            font_paths: [],
            ignore_system_fonts: false,
        },
    }
[2024-10-03T09:20:36Z INFO  sync_lsp] handling initialize - (0) at Instant { tv_sec: 5430869, tv_nsec: 252669164 }
[2024-10-03T09:20:36Z INFO  tinymist::init] preferred theme: Some("dark") {"compileStatus": String("enable"), "exportPdf": String("never"), "formatterMode": String("disable"), "formatterPrintWidth": Number(120), "onEnterEvent": Bool(true), "outputPath": String(""), "preferredTheme": String("dark"), "preview": Object {"cursorIndicator": Bool(false), "fontPaths": Array [], "invertColors": Null, "partialRendering": Bool(true), "pinPreviewFile": Bool(false), "refresh": String("onType"), "scrollSync": String("onSelectionChangeByMouse"), "sysInputs": Object {}, "systemFonts": Bool(true)}, "previewFeature": String("enable"), "semanticTokens": String("enable"), "systemFonts": Bool(true), "trace": Object {"server": String("messages")}, "typstExtraArgs": Array []}
[2024-10-03T09:20:36Z INFO  tinymist::server] LanguageState: initialized with config Config { const_config: ConstConfig { position_encoding: Utf16, cfg_change_registration: true, tokens_dynamic_registration: true, tokens_overlapping_token_support: false, tokens_multiline_token_support: false, doc_line_folding_only: true, doc_fmt_dynamic_registration: true }, compile: CompileConfig { roots: ["/home/coder/project/typst"], output_path: PathPattern(""), export_pdf: Never, root_path: None, font_opts: CompileFontArgs { font_paths: [], ignore_system_fonts: false }, system_fonts: Some(true), font_paths: [], fonts: OnceCell(Uninit), notify_status: true, periscope_args: None, typst_extra_args: Some(CompileExtraOpts { root_dir: None, entry: None, inputs: {}, font: CompileFontArgs { font_paths: [], ignore_system_fonts: false }, creation_timestamp: None, cert: None }), preferred_theme: Some("dark"), has_default_entry_path: false, lsp_inputs: {"x-preview": "{\"version\":1,\"theme\":\"dark\"}"} }, semantic_tokens: Enable, formatter_mode: Disable, formatter_print_width: Some(120) }
[2024-10-03T09:20:36Z INFO  tinymist::actor] TypstActor: creating server for primary, entry: EntryState { rooted: true, root: Some("/home/coder/project/typst"), main: None }, inputs: {"x-preview": "{\"version\":1,\"theme\":\"dark\"}"}
[2024-10-03T09:20:36Z INFO  tinymist::init] creating SharedFontResolver with CompileFontArgs { font_paths: [], ignore_system_fonts: false }
[2024-10-03T09:20:36Z INFO  sync_lsp] handled  initialize - (0) in 865.05µs
[Trace - 9:20:36 AM] Received response 'initialize - (0)' in 3ms.
[Trace - 9:20:36 AM] Sending notification 'initialized'.
[Trace - 9:20:36 AM] Sending request 'workspace/executeCommand - (1)'.
[Trace - 9:20:36 AM] Sending notification 'textDocument/didOpen'.
[Trace - 9:20:36 AM] Sending request 'workspace/executeCommand - (2)'.
[Trace - 9:20:36 AM] Sending request 'workspace/executeCommand - (3)'.
[2024-10-03T09:20:36Z INFO  sync_lsp] notifying initialized - at Instant { tv_sec: 5430869, tv_nsec: 258497913 }
[2024-10-03T09:20:36Z INFO  tinymist::server] server initialized
[2024-10-03T09:20:36Z INFO  sync_lsp] notifing initialized succeeded in 84.56µs
[Trace - 9:20:36 AM] Received request 'client/registerCapability - (0)'.
[Trace - 9:20:36 AM] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
[2024-10-03T09:20:36Z INFO  sync_lsp] handling workspace/executeCommand - (1) at Instant { tv_sec: 5430869, tv_nsec: 278596397 }
[Trace - 9:20:36 AM] Received request 'client/registerCapability - (1)'.
[Trace - 9:20:36 AM] Sending response 'client/registerCapability - (1)'. Processing request took 0ms
[2024-10-03T09:20:36Z INFO  sync_lsp] handled  workspace/executeCommand - (1) in 2.15ms
[2024-10-03T09:20:36Z INFO  sync_lsp] notifying textDocument/didOpen - at Instant { tv_sec: 5430869, tv_nsec: 280773629 }
[2024-10-03T09:20:36Z INFO  tinymist::server] did open Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/home/coder/project/typst/ml_kl.typ", query: None, fragment: None }
[2024-10-03T09:20:36Z INFO  tinymist::server] create source: "/home/coder/project/typst/ml_kl.typ"
[2024-10-03T09:20:36Z INFO  tinymist::actor::typ_client] the entry file of TypstActor(primary) is changing to EntryState { rooted: true, root: Some("/home/coder/project/typst"), main: Some(/ml_kl.typ) }
[2024-10-03T09:20:36Z INFO  tinymist::server] file focused[implicit,o]: Some("/home/coder/project/typst/ml_kl.typ")
[2024-10-03T09:20:36Z INFO  sync_lsp] notifing textDocument/didOpen succeeded in 166.11µs
[2024-10-03T09:20:36Z INFO  tinymist::actor::editor] received status request(primary) Compiling
[2024-10-03T09:20:36Z INFO  sync_lsp] handling workspace/executeCommand - (2) at Instant { tv_sec: 5430869, tv_nsec: 281108868 }
[2024-10-03T09:20:36Z INFO  tinymist::cmd] first manual focusing is coming
[2024-10-03T09:20:36Z INFO  sync_lsp] handled  workspace/executeCommand - (2) in 10.87µs
[2024-10-03T09:20:36Z INFO  sync_lsp] handling workspace/executeCommand - (3) at Instant { tv_sec: 5430869, tv_nsec: 284818904 }
[2024-10-03T09:20:36Z INFO  sync_lsp] handled  workspace/executeCommand - (3) in 782.13µs
[Trace - 9:20:36 AM] Received response 'workspace/executeCommand - (1)' in 36ms.
[2024-10-03T09:20:36Z INFO  tinymist::actor::editor] received diagnostics from primary:4: diag(Some(0))
[2024-10-03T09:20:36Z INFO  tinymist::actor::editor] received status request(primary) CompileSuccess
[2024-10-03T09:20:36Z INFO  tinymist::task::cache] CacheEvictTask: evict cache in 55.855µs
[2024-10-03T09:20:36Z INFO  tinymist::actor::editor] received status request(primary) Compiling
[2024-10-03T09:20:36Z INFO  tinymist::actor::editor] received diagnostics from primary:5: diag(Some(0))
[2024-10-03T09:20:36Z INFO  tinymist::actor::editor] received status request(primary) CompileSuccess
[2024-10-03T09:20:36Z INFO  tinymist::task::cache] CacheEvictTask: evict cache in 23.955µs
[Trace - 9:20:36 AM] Received notification 'tinymist/compileStatus'.
[Trace - 9:20:36 AM] Received response 'workspace/executeCommand - (2)' in 53ms.
[Trace - 9:20:36 AM] Received response 'workspace/executeCommand - (3)' in 54ms.
[Trace - 9:20:36 AM] Received notification 'tinymist/compileStatus'.
[Trace - 9:20:36 AM] Received notification 'tinymist/compileStatus'.
[Trace - 9:20:36 AM] Received notification 'tinymist/compileStatus'.
[Trace - 9:20:36 AM] Received notification 'tinymist/compileStatus'.
[Trace - 9:20:36 AM] Received notification 'tinymist/compileStatus'.
[Trace - 9:20:36 AM] Sending request 'textDocument/codeAction - (4)'.
[Trace - 9:20:36 AM] Sending request 'textDocument/documentColor - (5)'.
[2024-10-03T09:20:37Z INFO  sync_lsp] handling textDocument/codeAction - (4) at Instant { tv_sec: 5430869, tv_nsec: 429017986 }
[2024-10-03T09:20:37Z INFO  sync_lsp] handling textDocument/documentColor - (5) at Instant { tv_sec: 5430869, tv_nsec: 429079732 }
[2024-10-03T09:20:37Z INFO  sync_lsp] handled  textDocument/codeAction - (4) in 183.92µs
[2024-10-03T09:20:37Z INFO  sync_lsp] handled  textDocument/documentColor - (5) in 191.85µs
[Trace - 9:20:37 AM] Received response 'textDocument/codeAction - (4)' in 111ms.
[Trace - 9:20:37 AM] Received response 'textDocument/documentColor - (5)' in 112ms.
[Trace - 9:20:37 AM] Sending request 'workspace/executeCommand - (6)'.
[2024-10-03T09:20:37Z INFO  sync_lsp] handling workspace/executeCommand - (6) at Instant { tv_sec: 5430869, tv_nsec: 442008834 }
[2024-10-03T09:20:37Z INFO  tinymist::tool::preview] PreviewTask(m03rgm): arguments: PreviewCliArgs {
        preview: PreviewArgs {
            enable_partial_rendering: true,
            invert_colors: "never",
            task_id: "m03rgm",
            refresh_style: OnType,
        },
        compile: CompileOnceArgs {
            input: Some(
                "/home/coder/project/typst/ml_kl.typ",
            ),
            root: None,
            inputs: [],
            font: CompileFontArgs {
                font_paths: [],
                ignore_system_fonts: false,
            },
            creation_timestamp: None,
            certification: None,
        },
        preview_mode: Document,
        data_plane_host: "127.0.0.1:0",
        control_plane_host: "127.0.0.1:23626",
        static_file_host: "",
        not_as_primary: false,
        dont_open_in_browser: false,
    }
[2024-10-03T09:20:37Z INFO  typst_preview] Previewer: typst actor spawned
[2024-10-03T09:20:37Z INFO  typst_preview] Previewer: editor actor spawned
[2024-10-03T09:20:37Z INFO  tinymist::tool::preview] preview server listening on http://127.0.0.1:42111
[2024-10-03T09:20:37Z INFO  tinymist::tool::preview] PreviewTask(m03rgm): preview server listening on: 127.0.0.1:42111
[2024-10-03T09:20:37Z INFO  sync_lsp] handled  workspace/executeCommand - (6) in 2.97ms
[2024-10-03T09:20:37Z DEBUG typst_preview::actor::typst] TypstActor: waiting for message
[2024-10-03T09:20:37Z INFO  tinymist::actor::editor] received status request(primary) Compiling
[2024-10-03T09:20:37Z INFO  tinymist::actor::editor] received diagnostics from primary:6: diag(Some(0))
[2024-10-03T09:20:37Z INFO  tinymist::actor::editor] received status request(primary) CompileSuccess
[Trace - 9:20:37 AM] Received response 'workspace/executeCommand - (6)' in 5ms.
[2024-10-03T09:20:37Z INFO  tinymist::task::cache] CacheEvictTask: evict cache in 43.511µs
[Trace - 9:20:37 AM] Received notification 'tinymist/compileStatus'.
[Trace - 9:20:37 AM] Received notification 'tinymist/compileStatus'.
[Trace - 9:20:37 AM] Received notification 'tinymist/compileStatus'.
[Trace - 9:20:37 AM] Sending request 'textDocument/foldingRange - (7)'.
[2024-10-03T09:20:37Z INFO  sync_lsp] handling textDocument/foldingRange - (7) at Instant { tv_sec: 5430869, tv_nsec: 930370457 }
[2024-10-03T09:20:37Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 97.333µs
[2024-10-03T09:20:37Z INFO  sync_lsp] handled  textDocument/foldingRange - (7) in 186.06µs
[Trace - 9:20:37 AM] Sending request 'textDocument/documentSymbol - (8)'.
[Trace - 9:20:37 AM] Received response 'textDocument/foldingRange - (7)' in 72ms.
[2024-10-03T09:20:37Z INFO  sync_lsp] handling textDocument/documentSymbol - (8) at Instant { tv_sec: 5430870, tv_nsec: 1247200 }
[2024-10-03T09:20:37Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 95.038µs
[2024-10-03T09:20:37Z INFO  sync_lsp] handled  textDocument/documentSymbol - (8) in 237.53µs
[Trace - 9:20:37 AM] Received response 'textDocument/documentSymbol - (8)' in 2ms.
[Trace - 9:20:37 AM] Sending request 'textDocument/semanticTokens/full - (9)'.
[2024-10-03T09:20:37Z INFO  sync_lsp] handling textDocument/semanticTokens/full - (9) at Instant { tv_sec: 5430870, tv_nsec: 4002747 }
[Trace - 9:20:37 AM] Sending request 'textDocument/codeLens - (10)'.
[2024-10-03T09:20:37Z INFO  sync_lsp] handled  textDocument/semanticTokens/full - (9) in 220.28µs
[2024-10-03T09:20:37Z INFO  sync_lsp] handling textDocument/codeLens - (10) at Instant { tv_sec: 5430870, tv_nsec: 4677872 }
[2024-10-03T09:20:37Z INFO  sync_lsp] handled  textDocument/codeLens - (10) in 635.16µs
[Trace - 9:20:37 AM] Received response 'textDocument/semanticTokens/full - (9)' in 2ms.
[Trace - 9:20:37 AM] Received response 'textDocument/codeLens - (10)' in 1ms.
[Trace - 9:20:37 AM] Sending notification '$/setTrace'.
[Trace - 9:20:37 AM] Sending notification '$/setTrace'.
[Trace - 9:20:37 AM] Sending request 'textDocument/codeAction - (11)'.
[Trace - 9:20:37 AM] Sending request 'textDocument/codeAction - (12)'.
[Trace - 9:20:37 AM] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 9:20:37 AM] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 9:20:37 AM] Sending notification '$/cancelRequest'.
[2024-10-03T09:20:37Z INFO  sync_lsp] notifying $/setTrace - at Instant { tv_sec: 5430870, tv_nsec: 218230922 }
[2024-10-03T09:20:37Z WARN  sync_lsp] unhandled notification: $/setTrace
[2024-10-03T09:20:37Z INFO  sync_lsp] notifying $/setTrace - at Instant { tv_sec: 5430870, tv_nsec: 218982702 }
[2024-10-03T09:20:37Z WARN  sync_lsp] unhandled notification: $/setTrace
[2024-10-03T09:20:37Z INFO  sync_lsp] handling textDocument/codeAction - (11) at Instant { tv_sec: 5430870, tv_nsec: 219085785 }
[2024-10-03T09:20:37Z INFO  sync_lsp] handling textDocument/codeAction - (12) at Instant { tv_sec: 5430870, tv_nsec: 219295849 }
[2024-10-03T09:20:37Z INFO  sync_lsp] notifying workspace/didChangeConfiguration - at Instant { tv_sec: 5430870, tv_nsec: 219604458 }
[2024-10-03T09:20:37Z INFO  sync_lsp] notifing workspace/didChangeConfiguration succeeded in 34.11µs
[2024-10-03T09:20:37Z INFO  sync_lsp] notifying workspace/didChangeConfiguration - at Instant { tv_sec: 5430870, tv_nsec: 219706439 }
[2024-10-03T09:20:37Z INFO  sync_lsp] notifing workspace/didChangeConfiguration succeeded in 14.16µs
[2024-10-03T09:20:37Z INFO  sync_lsp] handled  textDocument/codeAction - (11) in 2.87ms
[2024-10-03T09:20:37Z INFO  sync_lsp] handled  textDocument/codeAction - (12) in 2.73ms
[Trace - 9:20:37 AM] Received request 'workspace/configuration - (2)'.
[Trace - 9:20:37 AM] Sending response 'workspace/configuration - (2)'. Processing request took 18ms
[2024-10-03T09:20:37Z INFO  sync_lsp] notifying $/cancelRequest - at Instant { tv_sec: 5430870, tv_nsec: 236458248 }
[2024-10-03T09:20:37Z WARN  sync_lsp] unhandled notification: $/cancelRequest
[Trace - 9:20:37 AM] Received request 'workspace/configuration - (3)'.
[Trace - 9:20:37 AM] Sending response 'workspace/configuration - (3)'. Processing request took 8ms
[2024-10-03T09:20:37Z INFO  tinymist::init] preferred theme: Some("dark") {"compileStatus": String("enable"), "exportPdf": String("never"), "fontPaths": Null, "formatterMode": String("disable"), "formatterPrintWidth": Number(120), "hoverPeriscope": Null, "outputPath": String(""), "preferredTheme": String("dark"), "rootPath": Null, "semanticTokens": String("enable"), "systemFonts": Bool(true), "typstExtraArgs": Array []}
[2024-10-03T09:20:37Z INFO  tinymist::server] new settings applied
[Trace - 9:20:37 AM] Received response 'textDocument/codeAction - (11)' in 43ms.
[2024-10-03T09:20:37Z INFO  tinymist::init] preferred theme: Some("dark") {"compileStatus": String("enable"), "exportPdf": String("never"), "fontPaths": Null, "formatterMode": String("disable"), "formatterPrintWidth": Number(120), "hoverPeriscope": Null, "outputPath": String(""), "preferredTheme": String("dark"), "rootPath": Null, "semanticTokens": String("enable"), "systemFonts": Bool(true), "typstExtraArgs": Array []}
[2024-10-03T09:20:37Z INFO  tinymist::server] new settings applied
[Trace - 9:20:37 AM] Received response 'textDocument/codeAction - (12)' in 46ms.
[Trace - 9:20:37 AM] Sending notification '$/setTrace'.
[Trace - 9:20:37 AM] Sending notification 'workspace/didChangeConfiguration'.
[2024-10-03T09:20:37Z INFO  sync_lsp] notifying $/setTrace - at Instant { tv_sec: 5430870, tv_nsec: 321670170 }
[2024-10-03T09:20:37Z WARN  sync_lsp] unhandled notification: $/setTrace
[2024-10-03T09:20:37Z INFO  sync_lsp] notifying workspace/didChangeConfiguration - at Instant { tv_sec: 5430870, tv_nsec: 321695587 }
[2024-10-03T09:20:37Z INFO  sync_lsp] notifing workspace/didChangeConfiguration succeeded in 36.71µs
[Trace - 9:20:37 AM] Received request 'workspace/configuration - (4)'.
[Trace - 9:20:37 AM] Sending response 'workspace/configuration - (4)'. Processing request took 1ms
[2024-10-03T09:20:37Z INFO  tinymist::init] preferred theme: Some("dark") {"compileStatus": String("enable"), "exportPdf": String("never"), "fontPaths": Null, "formatterMode": String("disable"), "formatterPrintWidth": Number(120), "hoverPeriscope": Null, "outputPath": String(""), "preferredTheme": String("dark"), "rootPath": Null, "semanticTokens": String("enable"), "systemFonts": Bool(true), "typstExtraArgs": Array []}
[2024-10-03T09:20:37Z INFO  tinymist::server] new settings applied
[Trace - 9:20:37 AM] Sending request 'textDocument/codeAction - (13)'.
[2024-10-03T09:20:37Z INFO  sync_lsp] handling textDocument/codeAction - (13) at Instant { tv_sec: 5430870, tv_nsec: 331203865 }
[2024-10-03T09:20:37Z INFO  sync_lsp] handled  textDocument/codeAction - (13) in 127.43µs
[Trace - 9:20:37 AM] Received response 'textDocument/codeAction - (13)' in 3ms.
[Trace - 9:20:38 AM] Sending notification '$/setTrace'.
[Trace - 9:20:38 AM] Sending notification 'workspace/didChangeConfiguration'.
[2024-10-03T09:20:38Z INFO  sync_lsp] notifying $/setTrace - at Instant { tv_sec: 5430870, tv_nsec: 737097722 }
[2024-10-03T09:20:38Z WARN  sync_lsp] unhandled notification: $/setTrace
[2024-10-03T09:20:38Z INFO  sync_lsp] notifying workspace/didChangeConfiguration - at Instant { tv_sec: 5430870, tv_nsec: 737390772 }
[2024-10-03T09:20:38Z INFO  sync_lsp] notifing workspace/didChangeConfiguration succeeded in 38.41µs
[Trace - 9:20:38 AM] Received request 'workspace/configuration - (5)'.
[Trace - 9:20:38 AM] Sending response 'workspace/configuration - (5)'. Processing request took 2ms
[Trace - 9:20:38 AM] Sending request 'textDocument/documentSymbol - (14)'.
[2024-10-03T09:20:38Z INFO  tinymist::init] preferred theme: Some("dark") {"compileStatus": String("enable"), "exportPdf": String("never"), "fontPaths": Null, "formatterMode": String("disable"), "formatterPrintWidth": Number(120), "hoverPeriscope": Null, "outputPath": String(""), "preferredTheme": String("dark"), "rootPath": Null, "semanticTokens": String("enable"), "systemFonts": Bool(true), "typstExtraArgs": Array []}
[2024-10-03T09:20:38Z INFO  tinymist::server] new settings applied
[2024-10-03T09:20:38Z INFO  sync_lsp] handling textDocument/documentSymbol - (14) at Instant { tv_sec: 5430870, tv_nsec: 747363250 }
[2024-10-03T09:20:38Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 106.78µs
[2024-10-03T09:20:38Z INFO  sync_lsp] handled  textDocument/documentSymbol - (14) in 276.68µs
[Trace - 9:20:38 AM] Received response 'textDocument/documentSymbol - (14)' in 2ms.
[Trace - 9:20:38 AM] Sending request 'textDocument/codeLens - (15)'.
[2024-10-03T09:20:38Z INFO  sync_lsp] handling textDocument/codeLens - (15) at Instant { tv_sec: 5430870, tv_nsec: 796551347 }
[2024-10-03T09:20:38Z INFO  sync_lsp] handled  textDocument/codeLens - (15) in 165.27µs
[Trace - 9:20:38 AM] Received response 'textDocument/codeLens - (15)' in 2ms.
[Trace - 9:20:40 AM] Sending request 'textDocument/codeAction - (16)'.
[Trace - 9:20:40 AM] Sending request 'textDocument/documentSymbol - (17)'.
[2024-10-03T09:20:40Z INFO  sync_lsp] handling textDocument/codeAction - (16) at Instant { tv_sec: 5430872, tv_nsec: 619272711 }
[2024-10-03T09:20:40Z INFO  sync_lsp] handling textDocument/documentSymbol - (17) at Instant { tv_sec: 5430872, tv_nsec: 619339406 }
[2024-10-03T09:20:40Z INFO  tinymist_query::syntax::lexical_hierarchy] lexical hierarchy analysis took 91.421µs
[2024-10-03T09:20:40Z INFO  sync_lsp] handled  textDocument/documentSymbol - (17) in 260.27µs
[2024-10-03T09:20:40Z INFO  sync_lsp] handled  textDocument/codeAction - (16) in 615.73µs
[Trace - 9:20:40 AM] Received response 'textDocument/documentSymbol - (17)' in 2ms.
[Trace - 9:20:40 AM] Received response 'textDocument/codeAction - (16)' in 2ms.
[Trace - 9:20:40 AM] Sending notification '$/setTrace'.
[Trace - 9:20:40 AM] Sending notification 'workspace/didChangeConfiguration'.
[2024-10-03T09:20:40Z INFO  sync_lsp] notifying $/setTrace - at Instant { tv_sec: 5430872, tv_nsec: 722349880 }
[2024-10-03T09:20:40Z WARN  sync_lsp] unhandled notification: $/setTrace
[2024-10-03T09:20:40Z INFO  sync_lsp] notifying workspace/didChangeConfiguration - at Instant { tv_sec: 5430872, tv_nsec: 722541950 }
[2024-10-03T09:20:40Z INFO  sync_lsp] notifing workspace/didChangeConfiguration succeeded in 34.08µs
[Trace - 9:20:40 AM] Received request 'workspace/configuration - (6)'.
[Trace - 9:20:40 AM] Sending response 'workspace/configuration - (6)'. Processing request took 2ms
[2024-10-03T09:20:40Z INFO  tinymist::init] preferred theme: Some("dark") {"compileStatus": String("enable"), "exportPdf": String("never"), "fontPaths": Null, "formatterMode": String("disable"), "formatterPrintWidth": Number(120), "hoverPeriscope": Null, "outputPath": String(""), "preferredTheme": String("dark"), "rootPath": Null, "semanticTokens": String("enable"), "systemFonts": Bool(true), "typstExtraArgs": Array []}
[2024-10-03T09:20:40Z INFO  tinymist::server] new settings applied
[Trace - 9:20:43 AM] Sending request 'workspace/executeCommand - (18)'.
[2024-10-03T09:20:43Z INFO  sync_lsp] handling workspace/executeCommand - (18) at Instant { tv_sec: 5430875, tv_nsec: 764240223 }
[2024-10-03T09:20:43Z INFO  sync_lsp] handled  workspace/executeCommand - (18) in 22.21µs
[Trace - 9:20:43 AM] Received response 'workspace/executeCommand - (18)' in 1ms.
[Trace - 9:20:44 AM] Sending request 'workspace/executeCommand - (19)'.
[2024-10-03T09:20:44Z INFO  sync_lsp] handling workspace/executeCommand - (19) at Instant { tv_sec: 5430876, tv_nsec: 978888696 }
[2024-10-03T09:20:44Z INFO  sync_lsp] handled  workspace/executeCommand - (19) in 31.94µs
[Trace - 9:20:44 AM] Received response 'workspace/executeCommand - (19)' in 1ms.

```

tinymist client log(Help -> Toggle Developer Tools -> Console):
```plain
Could not find it on code-server...
```

**Additional context**
- the server is running behind a traefik reverse-proxy on a subdomain: `code.domain.tld`
  - code-server is configured to expose ports on `code.domain.tld/proxy/<port>`
- This problem is similar to [Typst Preview fails on VSCode web and others. #382](https://github.com/Myriad-Dreamin/tinymist/issues/382)
- Documentation for code-server proxy configuration
  - https://coder.com/docs/code-server/guide#accessing-web-services
  - https://coder.com/docs/code-server/guide#using-your-own-proxy
```plain
### Accessing web services
If you're working on web services and want to access them locally, code-server can proxy to any port using either a subdomain or a subpath, allowing you to securely access these services using code-server's built-in authentication.
###
```

### PR DESCRIPTION
**Pull request by AllanChain**
Previously, Tinymist preview does not work on VS Code web (code-server) because it tries to connect to the `localhost`, which is impossible since we are doing remote development.

Even if we fix this error, the HTTP origin check will also fail because the domain of our VS Code web is not trusted by Tinymist. One possible fix is to grab the `VSCODE_PROXY_URI` environment variable and check if the incoming request matches the URI. This will fix the issue for most standard code-server installations.

However, GitHub Codespace is an exception. I did some logging, and found that GitHub Codespace used different origins:
- `<random>.assets.github.dev`
- `https://localhost:<port>` (note HTTP**S**)
- `None`

This is very weird and difficult to debug. Moreover, the ports forwarded by GitHub Codespaces require authentication before visiting, which the VS Code webview does not support. One have to open the URL in another browser tab to authenticate. This is frustrating and is difficult to workaround. Therefore, currently, GitHub Codespaces are not supported.

(I asked LLM to generate some of the Rust code. It works, but may need improvements.)

Fixes #625

### CODE REVIEW

File: crates/tinymist/src/tool/preview/http.rs [hunk 1]
```diff
@@ -210,6 +214,21 @@ fn is_valid_origin_impl(
...
+        let scheme = url.scheme();
+        let host = url.host_str()?;
+
+        let port_part = if let Some(port) = url.port() {
+            format!(":{port}")
+        } else {
+            String::new()
+        };
+
+        Some(format!("{scheme}://{host}{port_part}"))
```
Comment (Myriad-Dreamin) [inline crates/tinymist/src/tool/preview/http.rs]: what's the purpose of parsing URL and reformatting back to a URL? May turn to check by parsing and directly return a replaced content.
```rs
   let vscode_expected_origin = vscode_proxy_url.as_ref().and_then(|template| {
        let url_with_port = template.replace("{{port}}", &expected_port.to_string());
        let _url = Url::parse(&url_with_port).ok()?;
        Some(url_with_port)
```

**Review by Myriad-Dreamin — APPROVED** [review]
Thanks. It looks almost correct to me. I left a comment about formatting URL.

File: crates/tinymist/src/tool/preview/http.rs (hunk 1 above)
Comment (AllanChain) [reply crates/tinymist/src/tool/preview/http.rs]: I wanted to strip off the path and didn't know how to do it reliably in Rust. I asked LLM and it gave me the above code. I think your suggestion does not strip off the path part.

Comment (Myriad-Dreamin) [reply crates/tinymist/src/tool/preview/http.rs]: Oh, your explain it clearly. LLM gived me the answer:
```rs
Url::parse(&url_with_port).ok()?.origin().unicode_serialization()
```
Please take a look and test it.

Comment (AllanChain) [reply crates/tinymist/src/tool/preview/http.rs]: Yes, it works. I have updated the code.

**Review by Myriad-Dreamin — APPROVED** [review]

**Comment by AllanChain** [comment]
I have formatted the code as it failed CI.
